[package]
name = "persist"
version.workspace = true
edition.workspace = true

[dependencies]
lib = { path = "../lib" }
anyhow = "1.0.81"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
dirs = "5.0.1"
